name: telegram-agent-mcp-client

x-dns: &default-dns
  dns:
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-networks: &default-networks
  networks:
    - ai-agent

services:
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    #ports: # Not needed on host
    #  - 9091:9091 # Web UI port
    #  - 51413:51413 # Torrent port (TCP)
    #  - 51413:51413/udp # Torrent port (UDP)
    env_file:
      - docker-envs/transmission.env
    environment:
      - USER=${TRANSMISSION_USER:-}
      - PASS=${TRANSMISSION_PASS:-}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui|linuxserver/mods:transmission-transmissionic
    volumes:
      - transmission_config:/config
      - transmission_watch:/watch # change to your watch directory
      - /mnt/disk2/downloads:/downloads # change to your download directory
    <<: [*default-dns, *default-logging]
    network_mode: host # required for UPnP
    deploy:
      replicas: ${TRANSMISSION_ENABLE:-0}

  ygg-api:
    image: uwucode/ygege:develop
    container_name: ygg-api
    restart: unless-stopped
    ports:
      - 8715:8715
    volumes:
      - ygg-config:/config
    environment:
      LOG_LEVEL: debug
      BIND_IP: 0.0.0.0
      BIND_PORT: 8715
    env_file:
      - docker-envs/torrent_search.env
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8715/health || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 30s
    <<: [*default-dns, *default-logging, *default-networks]
    deploy:
      replicas: ${YGG_ENABLE:-1}

  # MCP services
  torrent-search-mcp:
    container_name: torrent-search-mcp
    image: philogicae/torrent-search-mcp:latest
    pull_policy: always
    command: torrent-search-mcp --mode sse
    restart: unless-stopped
    ports:
      - 8005:8000
    environment:
      - YGG_LOCAL_API=http://ygg-api:8715
    env_file:
      - docker-envs/torrent_search.env
    volumes:
      - torrents:/torrents
    <<: [*default-dns, *default-logging, *default-networks]

  transmission-mcp:
    container_name: transmission-mcp
    image: philogicae/transmission-mcp:latest
    pull_policy: always
    command: transmission-mcp --mode sse
    restart: unless-stopped
    ports:
      - 8006:8000
    env_file:
      - docker-envs/transmission.env
    volumes:
      - torrents:/torrents
    <<: [*default-logging, *default-networks]

networks:
  ai-agent:
    name: ai-agent
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: fd28:489c:c1d1::/64
          gateway: fd28:489c:c1d1::1

volumes:
  ygg-config:
  torrents:
  transmission_config:
  transmission_watch:
