name: telegram-agent-mcp-client

x-dns: &default-dns
  dns:
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

x-logging: &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-networks: &default-networks
  networks:
    - ai-agent

services:
  # External services
  # n8n:
  #   container_name: n8n
  #   image: docker.n8n.io/n8nio/n8n:next
  #   restart: unless-stopped
  #   ports:
  #     - 5678:5678
  #   env_file:
  #     - docker-envs/n8n.env
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   <<: [*default-dns, *default-logging, *default-networks]

  rqbit:
    container_name: rqbit
    image: ikatson/rqbit:main
    pull_policy: always
    restart: unless-stopped
    ports: # Not needed on host
      - 3030:3030 # HTTP API port
      - 4240:4240 # TCP/uTP BitTorrent port
    env_file:
      - docker-envs/rqbit.env
    volumes:
      - rqbit_db:/home/rqbit/db
      - rqbit_cache:/home/rqbit/cache
      - /mnt/disk2/downloads:/home/rqbit/downloads
    <<: [*default-dns, *default-logging, *default-networks]
    #network_mode: host # required for UPnP

  # MCP services
  torrent-search-mcp:
    container_name: torrent-search-mcp
    image: philogicae/torrent-search-mcp:latest
    pull_policy: always
    command: torrent-search-mcp --mode sse
    restart: unless-stopped
    ports:
      - 8005:8000
    env_file:
      - docker-envs/torrent_search.env
    volumes:
      - torrents:/torrents
    <<: [*default-dns, *default-logging, *default-networks]

  rqbit-mcp:
    container_name: rqbit-mcp
    image: philogicae/rqbit-mcp:latest
    pull_policy: always
    command: rqbit-mcp --mode sse
    restart: unless-stopped
    ports:
      - 8006:8000
    env_file:
      - docker-envs/rqbit.env
    volumes:
      - torrents:/torrents
    <<: [*default-logging, *default-networks]

networks:
  ai-agent:
    name: ai-agent
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
        - subnet: fd28:489c:c1d1::/64
          gateway: fd28:489c:c1d1::1

volumes:
  n8n_data:
  torrents:
  rqbit_db:
  rqbit_cache:
