name: telegram-agent-mcp-client

x-dns:
  &default-dns
  dns:
    - 9.9.9.9
    - 149.112.112.112
    - 2620:fe::fe
    - 2620:fe::9

x-logging:
  &default-logging
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "3"

x-networks:
  &default-networks
  networks:
    - ai-agent

services:
  telegram-agent:
    container_name: telegram-agent
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: telegram-agent
    restart: unless-stopped
    ports:
      - 8787:8000
    env_file:
      - ../.env
    <<: [*default-dns, *default-logging, *default-networks]

networks:
  ai-agent:
    name: ai-agent
    driver: bridge